apiVersion: v1
kind: ConfigMap
metadata:
  name: ingest-config
  namespace: better-bull-board
data:
  ENV: "production"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_USE_TLS: "false"
  WEBSOCKET_PORT: "8080"
  AUTO_DELETE_POSTGRES_DATA: "2592000"  # 30 days in seconds