name: better-bull-board
services:
  postgres:
    image: postgres:17
    container_name: better-bull-board_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: better-bull-board_redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

volumes:
  postgres-data:
  redis-data:
